sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm run test

after_sucess:
    - docker build -t quicklearninghub/multi-client ./client
    - docker build -t quicklearninghub/multi-server ./server
    - docker build -t quicklearninghub/multi-nginx ./nginx
    - docker build -t quicklearninghub/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push them to docker hub
    - docker push quicklearninghub/multi-client
    - docker push quicklearninghub/multi-server
    - docker push quicklearninghub/multi-nginx
    - docker push quicklearninghub/multi-worker